name: "Terraform Plan and Apply"

on:
  push:
    branches:
      - master
    paths:
      - 'terraform/**'
  pull_request:
    paths:
      - 'terraform/**'
  workflow_dispatch:

permissions:
  id-token: write  # This is required for AWS OIDC connection
  contents: read   # This is required for actions/checkout
  pull-requests: write  # This is required for GH bot to comment PR

env:
  TF_LOG: INFO
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./terraform
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: init
        env:
          AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
          AWS_BUCKET_KEY_NAME: ${{ secrets.AWS_BUCKET_KEY_NAME }}
          AWS_DYNAMODB_TABLE: ${{ secrets.AWS_DYNAMODB_TABLE }}
        run: |
          terraform init \
            -backend-config="bucket=${AWS_BUCKET_NAME}" \
            -backend-config="key=${AWS_BUCKET_KEY_NAME}" \
            -backend-config="region=${AWS_REGION}" \
            -backend-config="dynamodb_table=${AWS_DYNAMODB_TABLE}"

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        env:
          DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
          DOMAIN_NAME: ${{ secrets.DOMAIN_NAME }}
          ROUTE53_ZONE_ID: ${{ secrets.ROUTE53_ZONE_ID }}
          COGNITO_CALLBACK_URLS: ${{ secrets.COGNITO_CALLBACK_URLS }}
          COGNITO_LOGOUT_URLS: ${{ secrets.COGNITO_LOGOUT_URLS }}
          COGNITO_DOMAIN: ${{ secrets.COGNITO_DOMAIN }}
        run: |
          terraform plan \
            -no-color \
            -var "DATABASE_USERNAME=${DATABASE_USERNAME}" \
            -var "DATABASE_PASSWORD=${DATABASE_PASSWORD}" \
            -var "DATABASE_NAME=${DATABASE_NAME}" \
            -var "DOMAIN_NAME=${DOMAIN_NAME}" \
            -var "ROUTE53_ZONE_ID=${ROUTE53_ZONE_ID}"
            -var "COGNITO_CALLBACK_URLS=${COGNITO_CALLBACK_URLS}" \
            -var "COGNITO_LOGOUT_URLS=${COGNITO_LOGOUT_URLS}" \
            -var "COGNITO_DOMAIN=${COGNITO_DOMAIN}"
        if: github.event_name == 'pull_request'
        continue-on-error: true

      - uses: actions/github-script@v6
        if: github.event_name == 'pull_request'
        env:
          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // First, fetch all comments on the PR
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            });
            
            // Filter and delete comments made by the GitHub Actions bot
            const botComments = comments.filter(comment => {
              return comment.user.type === 'Bot' && 
                     comment.body.includes('Terraform Format and Style');
            });
            
            // Delete each previous bot comment
            for (const comment of botComments) {
              await github.rest.issues.deleteComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: comment.id
              });
              console.log(`Deleted comment ${comment.id}`);
            }
            
            // Create the new comment
            const output = `## Terraform Infrastructure Deployment 🚀
            ---
            #### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
            #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
            #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
            <details><summary>Validation Output</summary>

            \`\`\`\n
            ${{ steps.validate.outputs.stdout }}
            \`\`\`

            </details>

            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`

            <details><summary>Show Plan</summary>

            \`\`\`\n
            ${process.env.PLAN}
            \`\`\`

            </details>

            *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

      - name: Terraform Apply
        if: github.event_name == 'workflow_dispatch'
        env:
          DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
          DOMAIN_NAME: ${{ secrets.DOMAIN_NAME }}
          ROUTE53_ZONE_ID: ${{ secrets.ROUTE53_ZONE_ID }}
          COGNITO_CALLBACK_URLS: ${{ secrets.COGNITO_CALLBACK_URLS }}
          COGNITO_LOGOUT_URLS: ${{ secrets.COGNITO_LOGOUT_URLS }}
          COGNITO_DOMAIN: ${{ secrets.COGNITO_DOMAIN }}

        run: |
          terraform apply \
            -auto-approve \
            -var "DATABASE_USERNAME=${DATABASE_USERNAME}" \
            -var "DATABASE_PASSWORD=${DATABASE_PASSWORD}" \
            -var "DATABASE_NAME=${DATABASE_NAME}" \
            -var "DOMAIN_NAME=${DOMAIN_NAME}" \
            -var "ROUTE53_ZONE_ID=${ROUTE53_ZONE_ID}" \
            -var "COGNITO_CALLBACK_URLS=${COGNITO_CALLBACK_URLS}" \
            -var "COGNITO_LOGOUT_URLS=${COGNITO_LOGOUT_URLS}" \
            -var "COGNITO_DOMAIN=${COGNITO_DOMAIN}" \
            -input=false